// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: mapper.proto

package pbmanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicMapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicMapper) Reset() {
	*x = DynamicMapper{}
	mi := &file_mapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicMapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMapper) ProtoMessage() {}

func (x *DynamicMapper) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMapper.ProtoReflect.Descriptor instead.
func (*DynamicMapper) Descriptor() ([]byte, []int) {
	return file_mapper_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicMapper) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mapper_proto protoreflect.FileDescriptor

const file_mapper_proto_rawDesc = "" +
	"\n" +
	"\fmapper.proto\"v\n" +
	"\rDynamicMapper\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.DynamicMapper.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0eZ\f./;pbmanagerb\x06proto3"

var (
	file_mapper_proto_rawDescOnce sync.Once
	file_mapper_proto_rawDescData []byte
)

func file_mapper_proto_rawDescGZIP() []byte {
	file_mapper_proto_rawDescOnce.Do(func() {
		file_mapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapper_proto_rawDesc), len(file_mapper_proto_rawDesc)))
	})
	return file_mapper_proto_rawDescData
}

var file_mapper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mapper_proto_goTypes = []any{
	(*DynamicMapper)(nil), // 0: DynamicMapper
	nil,                   // 1: DynamicMapper.DataEntry
}
var file_mapper_proto_depIdxs = []int32{
	1, // 0: DynamicMapper.data:type_name -> DynamicMapper.DataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mapper_proto_init() }
func file_mapper_proto_init() {
	if File_mapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapper_proto_rawDesc), len(file_mapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapper_proto_goTypes,
		DependencyIndexes: file_mapper_proto_depIdxs,
		MessageInfos:      file_mapper_proto_msgTypes,
	}.Build()
	File_mapper_proto = out.File
	file_mapper_proto_goTypes = nil
	file_mapper_proto_depIdxs = nil
}
